# Site settings
title: Jari Oksanen's CV 
description: Jari Oksanen's CV 
favicon: /assets/img/bp_kuva_2020.jpg
baseurl: 
url: https://jarioksanen.github.io/resumecard
google_analytics: UA-63653234-1

# Sitemap for serach engines
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Jari Oksanen
  title: Kaizen & Transformation Leader
  address: Kauniaistenkatu 9 A, 24240 Salo, FINLAND
  email: j.oksanen@icloud.com
  # link: 
  # weibo:
  github: jarioksanen
  linkedin: www.linkedin.com/in/jari-johannes-oksanen
  twitter: oksanen_jari
  gavatar: /resumecard/assets/img/bp_kuva_2020.jpg
  # stackoverflow:
#  stackoverflow: 
  workHistory:
    - work1: XXX Ltd
      company: 
      location: 
      title: 
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: 
      title: 
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: 
      title: 
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: 
      degree: Bachelor
      major: 
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Finnish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Swedish
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 90%
    - skill4:
      name: React
      percentage: 90%
    - skill5:
      name: Java/Java EE
      percentage: 50%
    - skill6:
      name: Python
      percentage: 70%
