# Site settings
title: Jari Oksanen's CV 
description: Jari Oksanen's CV 
favicon: /assets/img/bp_kuva_2020.jpg
baseurl: 
url: https://jarioksanen.github.io/cv
google_analytics: UA-63653234-1

# Sitemap for search engines
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Jari Oksanen
  title: Kaizen & Transformation Manager
  address: Salo, FINLAND
  email: j.oksanen@icloud.com
  # link: 
  # weibo:
  github: jarioksanen
  linkedin: jari-johannes-oksanen
  twitter: oksanen_jari
  gavatar: /cv/assets/img/bp_kuva_2020.jpg
  workHistory:
    - work1: 
      company: Kyndryl Inc.
      location: Helsinki
      title: Kaizen & Transformation Manager
      started: 2021
      duration: (2021 - Present)
      description:
        "- Build tactical automation, tools, and analytics solutions for the organization.<br>
        - Deliver on time solutions that show positive impact and fast outcomes.<br>
        - Submit, monitor and quantify Kaizen opportunities through agreed tools and mgmt. System.<br>
        - Actively identify improvement opportunities and synergies for the organization.<br>
        - Provide overall Tactical & Strategic Kaizen Transformational support to the operational teams.<br>
        - Support the Business Process Owners to ensure that the right people are support the change activities, and to escalate potential issues or conflicts.<br>
        - Support the change management to maximize the expected benefits of the transformation.<br>
        - Lead & manage Kaizen projects.<br>
        - Project plans utilizing agile/design thinking methodologies.<br>
        - Integrate local Process/documentation/audit requirements.<br>
        - Keep stakeholders updated on status.<br>
        - Ensure the change impact of the transf. portfolio causes minimum business disruption.<br>"
    - work2:
      company: IBM Corp.
      location: Helsinki
      title: Tactical Kaizen Leader for EMEA
      started: 2020
      duration: (2020 - 2021)
      description: This role supports organizational and cultural transformation by working with internal and external clients to drive process excellence and identify opportunities for improvement. People in this role need to understand the needs and the environment of the organization as well as current processes, process results and process maturity. They lead, perform and coach efforts targeted at improving operational aspects of a given value stream or process such as quality, cost, cycle time and overall performance. Work activities include identification of best practices, factors contributing to performance gaps, areas for change, and process success measurement criteria. Focus is placed on continuous incremental and breakthrough process improvement using a fundamental set of principles and consistent application of the scientific methodology. They may apply a variety of tools and techniques such as Business Process Management (BPM), Lean, Lean Six Sigma, Agile and Design for Operational eXcellence (DOX) and provide instruction and guidance to others in effective use of these approaches.
    - work3:
      company: IBM Corp.
      location: Helsinki
      title: E2E Cross market Support EMEA
      started: 2018
      duration: (2018 - 2021)
      description: "Support all AM Europe Squads by transforming and optimizing delivery of European AM services<br>
       - Automation, Simplification, Reporting, Standardization<br>
       - Geo specific Projects & Initiatives<br>
       - Working with owners to improve policies, processes and tools to optimize delivery the customers in Europe<br>
       - Ensuring delivered E2E services at all times are relevant for the customers in Europe"
    - work4:
      company: IBM Corp.
      location: Helsinki
      title: EMEA IT Logistics Service Line Owner
      started: 2014
      duration: (2014 - 2018)
      description: "Overall delivery lead for Asset Management Logistics service line in Europe<br>
       - Cost effectiveness of services<br>
       - Quality and continuous improvement of services<br>
      <br>
      Drives European consistency of AM Logistics service line<br>
       - Service definitions<br>
       - Organizational structure<br>
       - Operational processes<br>
       - Tools"
    - work5:
      company: IBM Corp.
      location: Helsinki
      title: Nordic HW AM & IT Logistics Process Owner
      started: 2011
      duration: (2011 - 2014)
      description: "Top Level Responsibilities:<br>
       - Acts as process advisor to AM-team and secure/maintain effective processes and working instructions within the responsibility area<br>
       - Establishes and maintains good and effective relationship & team work across competencies and within accounts and Asset Management team<br>
       - Ensures and maintains a high control posture through efficient execution in line with Asset Mgmt Best Practice processes and control points.<br>
       - Works actively to support IT-Delivery strategies including Globalization efforts and continued focus on cost effectiveness.<br>
       - Proactively supports deployment of Asset Mgmt project Milestones, compliance and/or process optimization programs."
  educationHistory:
    - education1:
      organization: Turku University of Applied Sciences
      location: Salo
      degree: Bachelor
      major: Engineering, Information and Communications Technology
      started: 2012
      duration: (2012 - 2015)
      description: 
  languages:
    - language1:
      name: Finnish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Swedish
      proficiency: Limited
  certificates:
    - certificate:
      name: Big Data Foundations - Level 2 (V2)
      IssuedBy: IBM
      name: Blue Prism Certified Developer
      IssuedBy: Blue Prism
    - certificate:
      name: Certified Software Asset Management Professional
      IssuedBy: BSA | The Software Alliance
    - certificate:
      name: Data Science Foundations - Level 2 (V2)
      IssuedBy: IBM
    - certificate:
      name: Enterprise Design Thinking pratitioner
      IssuedBy: IBM
    - certificate:
      name: IBM Consultant
      IssuedBy: IBM
    - certificate:
      name: Microsoft Certified Azure Fundamentals
      IssuedBy: Microsoft
    - certificate:
      name: Microsoft Certified Azure Data Fundamentals
      IssuedBy: Microsoft
    - certificate:
      name: Microsoft Certified Power Platform App Maker Associate
      IssuedBy: Microsoft
    - certificate:
      name: Microsoft Certified Power Platform Fundamentals
      IssuedBy: Microsoft
    - certificate:
      name: Scrum Foundation Professional Certificate
      IssuedBy: CertiProf
  itSkills:
    - skill:
      name: Azure
      percentage: 60%
    - skill:
      name: Blockchain
      percentage: 60%
    - skill:
      name: Change Management
      percentage: 80%
    - skill:
      name: Cloud
      percentage: 60%
    - skill:
      name: Data Analytics
      percentage: 70%
    - skill:
      name: Incident Management
      percentage: 70%
    - skill:
      name: IT Asset Management
      percentage: 90%
    - skill:
      name: IT Operations
      percentage: 70%
    - skill:
      name: Process Management
      percentage: 80%
    - skill:
      name: Supply Chain Management
      percentage: 80%
  programmingSkills:
    - skill1:
      name: CSS
      percentage: 60%
    - skill2:
      name: HTML
      percentage: 70%
    - skill3:
      name: Java/Java EE
      percentage: 60%
    - skill4:
      name: JavaScript
      percentage: 60%
    - skill5:
      name: Node.js
      percentage: 60%
    - skill6:
      name: Power Platform
      percentage: 80%
    - skill7:
      name: Python
      percentage: 60%
    - skill8:
      name: React
      percentage: 60%
    - skill9:
      name: RPA
      percentage: 80%
    - skill10:
      name: SQL
      percentage: 70%